# Generated by Django 4.2.5 on 2023-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, verbose_name='rakuten_product_id')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('video_url', models.TextField(verbose_name='video_url')),
                ('shop_code', models.CharField(max_length=100, verbose_name='shop_code')),
            ],
        ),
    ]
